### ISSUE TITLE
render called multiple times per commit

### ISSUE THREAD

**Issue by chisholmd** [hankchizljaw/vanilla-js-state-management#3]
If I commit an object like this to the store, render is being called multiple times
{
  someProp: 123
  otherProp: ABC
  someArray: [{val:val,val:vcal}]
}

Is that by design or have I messed something up?

**Comment by Andy-set-studio** [comment]
Hey there! 

This was fixed on Beedle, which is the OS packaged version of this older library: https://github.com/hankchizljaw/beedle/issues/18

**Comment by chisholmd** [comment]
Thanks... and sorry for being a bit thick but I don't seem to speak enough github to find the fix.  I read the thread and get the ghist of it, but where is the new code?

**Comment by chisholmd** [comment]
Oh I think I see, there is a new prohject called Beedle.  So perhaps I have to use the whole new code base instead of this sample project.

**Comment by Andy-set-studio** [comment]
Yeh I think now that is probably the best bet to be honest 👍
